[package]
name = "amdb-geo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.12"
geo = "0.27.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
